library(dplyr)
library(ggmap)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyr)
library(stringr)
crimedata <- read.csv("Crime_Data_2010_2017.csv")
crimedata<-tbl_df(crimedata)
glimpse(crimedata)
str(crimedata)

crimedata$Date.Reported_C <- as.Date(crimedata$Date.Reported, format=("%m/%d/%Y"))
crimedata$Date.Occurred_C <- as.Date(crimedata$Date.Occurred, format=("%m/%d/%Y"))

#Separating Dates
crimedata$Date.Occurred <- mdy(LACrime$Date.Occurred)
crimedata$Date.Reported <- mdy(LACrime$Date.Reported)
crimedata <- separate(crimedata, col=Date.Occurred, into=c('Year.Occurred','Month.Occurred', "Day.Occurred"), sep="-")
crimedata <- separate(crimedata, col=Date.Reported, into=c('Year.Reported','Month.Reported', "Day.Reported"), sep="-")
Crime2016 <- filter(crimedata,Year.Reported < 2017)

#Race variable 
Crime2016[, "Victim.Descent"] <- sapply(Crime2016[, "Victim.Descent"], as.character)
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "W", "White")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "B", "Black")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "H", "Hispanic")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "A", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "C", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "J", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "K", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "F", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "C", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "L", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "D", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "V", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "Z", "Asian")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "O", "Others")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "G", "Others")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "X", "Others")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "I", "Others")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "P", "Pacific Islander")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "S", "Pacific Islander")
Crime2016$Victim.Descent <- str_replace(Crime2016$Victim.Descent, "U", "Pacific Islander")
Crime2016[, "Victim.Descent"] <- sapply(Crime2016[, "Victim.Descent"], as.factor)
summary(Crime2016$Victim.Descent)

#Non-vehicle crime (race is nil implies that vehicle crime
pplcrime <- filter(Crime2016, Crime2016$Victim.Descent!="")
ggplot(data=pplcrime, aes(x=Victim.Age, fill=Victim.Descent)) + geom_histogram() + facet_wrap(~Year.Reported) + labs(x="Victim's Age", y="Number of Crimes")

